version: '3.9'
services:
  opentrashmail:
    build:
      context: .
      dockerfile: docker/Dockerfile

    volumes:
      - './:/var/www/opentrashmail'
    environment:
      - URL=http://localhost:8080
      - DOMAINS=example.com
      - DATEFORMAT=D.M.YYYY HH:mm
      - SKIP_FILEPERMISSIONS=true
      - DISCARD_UNKNOWN=false
      - SHOW_ACCOUNT_LIST=true
      - SHOW_LOGS=true
      # - PASSWORD=123456
      # - ALLOWED_IPS=192.168.0.0/16,2a02:ab:cd:ef::/60
      # - ATTACHMENTS_MAX_SIZE=10000000

    ports:
      - '2525:25'
      - '8080:80'